---
name: "\U0001F680 Feature Request"
description: Request new features
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature you want to add.
      placeholder: Feature description
    validations:
      required: true
---

<!-- This issue template is required to be filled out. -->
< ! -- required_template: true -->
