name: Ruff linter and formatter

on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  ruff_lint_and_format:
    runs-on: ubuntu-latest
    env:
      UV_HTTP_TIMEOUT: 600 # max 10min to install deps

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.13

      # Setup venv
      - name: Setup venv + uv
        run: |
          pip install --upgrade uv
          uv venv

      # Install Ruff from requirements-dev.txt
      - name: Install Ruff
        run: |
          uv pip install "ruff==$(grep -oP '(?<=ruff==).*' requirements-dev.txt)"

      - name: Ruff Linter
        run: .venv/bin/ruff check bot tests

      - name: Ruff Formatter 
        run: .venv/bin/ruff format bot tests